package com.email.writer.repository;

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import com.email.writer.model.EmailRequest;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@Repository
public class EmailGenratorRepoImpl implements EmailGenratorRepo {

    private static final Logger log = LoggerFactory.getLogger(EmailGenratorRepoImpl.class);

    private final WebClient wc;
    private final ObjectMapper mapper = new ObjectMapper();

    public EmailGenratorRepoImpl(WebClient.Builder builder) {
        this.wc = builder.build();
    }

    @Value("${gemini.api.url:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}")
    private String geminiApiUrl;

    @Value("${gemini.api.key:}")
    private String geminiApiKey;

    @Override
    public String emailReply(EmailRequest er) {
        // Validate API Key
        if (geminiApiKey == null || geminiApiKey.trim().isEmpty()) {
            return "Configuration Error: Gemini API key is missing. Please set 'gemini.api.key' in application.properties or set the GEMINI_API_KEY environment variable.";
        }

        // Build the prompt
        String prompt = buildPrompt(er);

        // Craft request body for Gemini API
        Map<String, Object> requestbody = Map.of(
            "contents", new Object[]{
                Map.of("parts", new Object[]{
                    Map.of("text", prompt)
                })
            }
        );

        try {
            // Execute request
            String response = wc.post()
                .uri(geminiApiUrl + "?key=" + geminiApiKey.trim())
                .header("Content-Type", "application/json")
                .bodyValue(requestbody)
                .retrieve()
                .bodyToMono(String.class)
                .block();

            return extractResponse(response);
        } catch (WebClientResponseException e) {
            log.error("Gemini API error status: {}, body: {}", e.getStatusCode(), e.getResponseBodyAsString(), e);
            try {
                JsonNode errNode = mapper.readTree(e.getResponseBodyAsString());
                if (errNode.has("error") && errNode.path("error").has("message")) {
                    return "Gemini API Error (" + e.getStatusCode() + "): " + errNode.path("error").path("message").asText();
                }
            } catch (Exception ignored) {
            }
            return "Gemini API Error: " + e.getStatusCode() + " - " + e.getStatusText();
        } catch (Exception e) {
            log.error("Failed to generate email reply", e);
            return "Error generating email reply: " + e.getMessage();
        }
    }

    private String extractResponse(String response) {
        try {
            JsonNode rootNode = mapper.readTree(response);

            // Check if error node exists
            if (rootNode.has("error")) {
                return "Gemini Error: " + rootNode.path("error").path("message").asText();
            }

            JsonNode candidates = rootNode.path("candidates");
            if (candidates.isArray() && !candidates.isEmpty()) {
                JsonNode firstCandidate = candidates.get(0);
                JsonNode parts = firstCandidate.path("content").path("parts");
                if (parts.isArray() && !parts.isEmpty()) {
                    String reply = parts.get(0).path("text").asText();
                    if (reply != null && !reply.trim().isEmpty()) {
                        return reply.trim();
                    }
                }
            }

            return "Unable to generate reply: No text generated by AI model.";
        } catch (Exception e) {
            log.error("Error parsing Gemini response: {}", response, e);
            return "Error parsing response: " + e.getMessage();
        }
    }

    private String buildPrompt(EmailRequest er) {
        StringBuilder prompt = new StringBuilder();
        prompt.append("You are an expert email assistant. Write a high-quality, professional, and context-aware email reply to the message below.\n\n");
        prompt.append("Guidelines:\n");
        prompt.append("- Do NOT include a subject line (do not write 'Subject:').\n");
        prompt.append("- Write ONLY the reply email body ready to be sent directly.\n");
        prompt.append("- Keep it polite, concise, and clear.\n");

        if (er.getTone() != null && !er.getTone().trim().isEmpty() && !er.getTone().trim().equalsIgnoreCase("none")) {
            prompt.append("- Use a ").append(er.getTone().trim()).append(" tone throughout the response.\n");
        }

        prompt.append("\nOriginal Email:\n\"\"\"\n")
              .append(er.getEmailContent().trim())
              .append("\n\"\"\"\n");

        return prompt.toString();
    }
}
