spring.application.name=email-writer-3
server.port=8080

# Gemini API Configuration
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent
gemini.api.key=
